singer-io/tap-zendesk

tap_zendesk/schemas/tickets.json
Adding some additional fields to the schema.
=> Add satisfaction rating

tap_zendesk/schemas/ticket_forms.json, tap_zendesk/streams.py
Adding ticket_forms stream to tap
=> add ticket forms

CHANGELOG.md, setup.py
bump version to 1.4.7
- n/a
None
=> bump version to 1.4.7

.circleci/config.yml
Add cron to circle config to run tests against master once per day
- 
- 
=> add cron to circle config, run once per day

CHANGELOG.md, setup.py
bump version to 1.5.0
- none
- low
=> bump version to 1.5.0

CHANGELOG.md, setup.py
Version 1.5.3 and changelog
- none
- low
=> Version 1.5.3 and changelog

setup.py
This PR pins `pylint` to the latest working version
- Ran `pylint` locally
- Low
=> Pin pylint version

CHANGELOG.md, setup.py
Version bump for #67 
- See #67 
- See #67 
- revert #67  branch and bump the version
=> Bump to v1.5.7, update changelog

CHANGELOG.md, setup.py
Version bump for #70 
- See #70 
- See #70 
- revert #70  branch and bump the version
=> Bump to v1.5.8, update changelog

.circleci/config.yml, test/base.py, test/test_all_fields.py, test/test_automatic_fields.py, test/test_discovery.py, test/test_pagination.py, test/test_standard_bookmark.py, test/test_start_date.py
- Added following below integration tests
- Start Date Test
- Pagination Test
- Automatic Fields Test
- All Fields Test
- Bookmark Test
- Discovery Test
- 
- 
=> Tdl 15582 check best practices

CHANGELOG.md, setup.py
Bump version to promote Crest Changes for Zendesk
- 
- 
=> Bump version 1.7.0

CHANGELOG.md, setup.py
By mistake I created a PR as 1.8.0. It should be 1.7.1 as this is a fix to 1.7.0 which failed in previous release
- 
- 
=> Bump version 1.7.1

tap_zendesk/http.py, test/unittests/test_http.py
- Reverted back backoff changes for 503 error code
- Updated unit test cases for the same
- Run sync mode and raise manually 503 error. Verify that backoff works properly for the 503 error code.
- 
=> TDL-16583 Update backoff for 503 error code

CHANGELOG.md, setup.py
Bump Version For Request Timeout
- 
- 
=> Bump Version for Zendesk Request TimeOut

test/test_bookmarks.py
Rip singer methods from tests. 
- Fixes double logging from test output
- Increases confidence in test
- 
- 
=> rip singer methods from tests

test/test_automatic_fields.py
Linked  BUG TDL-19428 in failing auto fields test. Skipped failing stream.
- 
- 
=> bug linked for duplicates, test workaround

test/base.py, test/test_all_streams.py
when retrying a sync due to failure there could be state that needs to be reset, allow for this.
- run the test forcing a failure
- 
=> tap tester stability

test/test_all_streams.py
This reverts commit dddd8f3686ab0d982870845a66efa5b569ef0678.
- 
Low
=> Revert commit dddd8f3

CHANGELOG.md, setup.py
Major version bump 2.0.0
- None
- Low risk
=> Major version bump 2.0.0

test/base.py, test/test_start_date.py
Handle the unix time stamp 
- 
- low
=> fix-startdate-unixtimestamp

test/base.py, test/test_all_fields.py, test/test_all_streams.py, test/test_automatic_fields.py, test/test_bookmarks.py, test/test_custom_fields_discover.py, test/test_discovery.py, test/test_minimal_selection.py, test/test_pagination.py, test/test_standard_bookmark.py, test/test_start_date.py
https://jira.talendforge.org/browse/TDL-20862
Removed some unused imports across tests.  Replaced one singer import with base function to prevent double logging.
- 
- 
=> Use skipUnless to mute Tier 1 tap errors until issue resolved

test/test_all_fields.py, test/test_lookup_fields.py
Update users stream to expect chat_only field
- 
- 
=> Update users stream to expect chat_only field

.circleci/config.yml, CHANGELOG.md, setup.py, tap_zendesk/discover.py, tap_zendesk/streams.py, tap_zendesk/sync.py
Updates to run tap on python 3.11
- 
- 
=> Updates for python 3.11

CHANGELOG.md, setup.py
- Update tap-version in setup.py
- 
- 
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code
=> TDL-26714: Update tap-version in setup.py

.circleci/config.yml
https://qlik-dev.atlassian.net/browse/SAC-28339
- 
- 
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code
=> SAC-28339: update circle config to use uv
