singer-io/tap-zendesk

tap_zendesk/schemas/group-memberships.json
tap_zendesk/schemas/groups.json
tap_zendesk/schemas/macros.json
tap_zendesk/schemas/organizations.json
tap_zendesk/schemas/ticket-fields.json
tap_zendesk/schemas/ticket-metrics.json
tap_zendesk/schemas/tickets.json
tap_zendesk/schemas/users.json

Taking the streams that are currently available in master and generating up to date schemas for them to capture all of the possible values that we have available.
`organization-fields` and `user-fields` are currently marked with `"additionalProperties":true` for the time being, until we can figure out how to handle them.

Updating streams from master

---

tap_zendesk/discover.py
tap_zendesk/schemas/group-memberships.json
tap_zendesk/schemas/groups.json
tap_zendesk/schemas/macros.json
tap_zendesk/schemas/organizations.json
tap_zendesk/schemas/ticket-audits.json
tap_zendesk/schemas/ticket-fields.json
tap_zendesk/schemas/ticket-metrics.json
tap_zendesk/schemas/tickets.json
tap_zendesk/schemas/users.json
tap_zendesk/streams.py

* Sets replication-keys to 'automatic'
* Removes "fields" because they duplicate "custom-fields"
* Skips tickets that come back by accident

Schema Updates and various fixes

---

tap_zendesk/streams.py

This refactor happened but wasn't working for Tags as it has a different set of key properties.
Also found that Tags (which uses FULL_TABLE replication) was writing an array of `[null]` which wasn't hurting but looked silly.

Use the instances key_properties instead of the constant

---

setup.py
tap_zendesk/schemas/organizations.json

Organization fields has a dynamic schema, when there are no custom fields, the "properties" is an empty object. Singer python recently received a fix to handle this case properly, so bumped it to 5.1.5 for that.
Also, added `deleted_at` to the organizations schema, since it was coming back in the API response.

Fix organization fields schema issue

---

tap_zendesk/discover.py
tap_zendesk/schemas/shared/metadata.json
tap_zendesk/schemas/shared/via.json
tap_zendesk/schemas/ticket_comments.json
tap_zendesk/streams.py

- Fixes a bug where some `group_membership` records were being returned without an `updated_at` field.  The solution is to check for the `updated_at`, and if it is not present, log an info message and sync it.  This means records without an `updated_at` field will be sync'd on every run.
- Fixes schema refs by adding `shared/`

Fix refs and group memberships

---

tap_zendesk/schemas/sla_policies.json
tap_zendesk/streams.py

This PR adds the `sla_policies` stream according to https://developer.zendesk.com/rest_api/docs/core/sla_policies#sla-policies.
This uses Zenpy SlaPolicy API and should conform to the rest of the streams.
I've tried to make the JSONSchema as narrow as possible.

Add SLA Policy stream

---

tap_zendesk/schemas/ticket_comments.json
tap_zendesk/streams.py

Adds `ticket_id` to `ticket_comments` stream so users can link the comments back to corresponding ticket.

add ticket_id to ticket_comments stream

---

tap_zendesk/__init__.py
tap_zendesk/metrics.py
tap_zendesk/streams.py

Motivation
----------
https://stitchdata.atlassian.net/browse/SUP-279: Zendesk `tickets`
replication is too slow for us to ever finish
We believe that the substream strategy in this tap leads clients to be
unable to replicate their data fast enough to keep up with time. We think
this is intrinsic to the way Zendesk exposes their data but for the time
being we're going to start capturing and logging rates to facilitate and
measure optimization later.

Capture and Log Runtime Performance Metrics for Use in Optimization

---

Makefile
setup.py
tap_zendesk/__init__.py
test/test_init.py

In order to properly use a Partner app with the Zendesk API, some headers need to be specified with each request as outlined [in this article](https://develop.zendesk.com/hc/en-us/articles/360001934648).
This PR gives the option of adding these three values in the config using the keys `["marketplace_name", "marketplace_organization_id", "marketplace_app_id"]`.

Add option to specify partner config and test

---

tap_zendesk/__init__.py

Fixes #25
Tests passing and metric being recorded:
```
2019-06-27 05:08:25,252Z    tap - INFO METRIC Point(metric_type='timer', metric='http_request_duration', value=0.18338823318481445, tags={'status': 'succeeded', 'endpoint': '/api/v2/tickets/657/metrics.json'})
2019-06-27 05:08:25,489Z    tap - INFO METRIC Point(metric_type='timer', metric='http_request_duration', value=0.22989487648010254, tags={'status': 'succeeded', 'endpoint': '/api/v2/tickets/658/audits.json'})
2019-06-27 05:08:25,678Z    tap - INFO METRIC Point(metric_type='timer', metric='http_request_duration', value=0.18178319931030273, tags={'status': 'succeeded', 'endpoint': '/api/v2/tickets/658/metrics.json'})
```

Patch Session.request to track http_request_timer metrics

---

tap_zendesk/__init__.py
tap_zendesk/sync.py

The `Transformer` was being created for each record, but now we create it once per stream.

Reduce log noise

---

tap_zendesk/streams.py

Use `start_time` query parameter for satisfaction_ratings stream.
The `start_time` query parameter for `satisfaction_ratings` allows you to only retrieve satisfaction_ratings with a `created_at > start_time`.  After testing, we found that updating satisfaction_ratings actually creates new records so that `created_at = updated_at` for all ratings.  Therefore, we can still bookmark on `updated_at` and query on `created_at`.
-  Created a satisfaction_rating, syncd it, updated the rating, syncd again and verified that only the new updated rating came back
- None

Use start_time for satisfaction_ratings stream

---

CHANGELOG.md
setup.py
tap_zendesk/streams.py

added error message, bumped version to 1.5.1
- 
- low

added error message, bumped version to 1.5.1

---

CHANGELOG.md
setup.py
tap_zendesk/streams.py

added retry logic for users stream
- ran tests
- low

added retry logic for users stream

---

tap_zendesk/streams.py
test/test_bookmarks.py

Break out of infinite loop and bookmark on date window end
- ran a sync to make sure records were still coming through
- low

Break out of infinite loop and bookmark on date window end

---

CHANGELOG.md
setup.py
tap_zendesk/__init__.py

This PR adds logging around every request of the URL, the response ETag, and the Request ID in order to pass these values along to Zendesk support in the event of an error.
- Relying on tests to run a sync for every stream
- Manually tested with the Users stream to confirm no sensitive information is logged
- Low, it's a logging add that's relatively safe (credentials should not be part of the URL string, these are contained within the session itself)

v1.5.4: Log request URL, etag, and request ID for debugging purposes

---

CHANGELOG.md
setup.py

This is the version bump for #64 
- See #64 
- See #64 
- revert #64 branch and bump the version

Bump to v1.5.5, update changelog

---

CHANGELOG.md
setup.py
tap_zendesk/streams.py

Log the bad user ids
- Forced the exception code to run and verified the user ids printed out in the log line as expected.
- 

Log the bad user ids

---

tap_zendesk/streams.py

This PR partially reverts #64, changing the Organizations stream back to the Search endpoint
- None
- Low since this worked before

Revert Organizations to the Incremental Search endpoint

---

CHANGELOG.md
setup.py
tap_zendesk/http.py
tap_zendesk/streams.py

https://jira.talendforge.org/browse/TDL-15551
Fixing the `via.from` field on the `tickets`,  and `ticket_comments` stream.
The previous version bump on the `zenpy` library changed how the `zenpy` was returning the `via.from` field to `via._from`. To work around this we are dropping the usage of the `zenpy` library for the `tickets` stream and all children streams.
- tests will run in circle
- that's it for now
- if we implement the sync and pagination correctly, there should be no risks

Remove Zenpy usage for Tickets stream

---

.circleci/config.yml
setup.py
tap_zendesk/__init__.py
tap_zendesk/discover.py
tap_zendesk/http.py
tap_zendesk/streams.py
test/base.py
test/test_all_fields.py
test/test_automatic_fields.py
test/test_discovery.py
test/test_pagination.py
test/test_standard_bookmark.py
test/test_start_date.py
test/unittests/test_discovery_mode.py
test/unittests/test_exception.py
test/unittests/test_http.py
test/unittests/test_request_timeout.py
test/unittests/test_tickets_child_stream_skip_404_error.py
test/unittests/test_yield_records.py

- https://github.com/singer-io/tap-zendesk/pull/78
- https://github.com/singer-io/tap-zendesk/pull/77
- https://github.com/singer-io/tap-zendesk/pull/74
- https://github.com/singer-io/tap-zendesk/pull/69
- Verify all implemented functionality once. 
- 

Tdl 14624 crest master

---

.circleci/config.yml
tap_zendesk/discover.py
test/unittests/test_discovery_mode.py

- Revert backed API access change in discover mode.
- Now, if at least one stream have read permission then tap just print warning message for all streams which does not have read permission
- If any one of stream does not have read permission then raise error.
- Create access token with limited scope and verify tap behaviour.
- 

Tdl 16369 revert back api access change

---

CHANGELOG.md
setup.py

Bump version for zendesk to take care of API Access logic change
- 
- 

Bump version 1.8.0

---

tap_zendesk/http.py
test/unittests/test_http.py

- Added back retry mechanism for all 5xx errors.
- Added unit test cases for 524 and 520 errors.
- Raise Httperror with status code 524 and 520 error and verify retry.
- 

Backoff for all 5xx errors

---

CHANGELOG.md
setup.py

This bump version is to take care of 520 and 524 Errors that were encountered in 1.7.1 release. Now we are going to try for all errors rather than specific errors as mentioned in Zendesk Documentation
- 
- 

Bump version 1.7.2

---

CHANGELOG.md
setup.py

Found couple of transactions for a set of customers not doing retry for 503 errors. This bump version is to fix the retry for 503 errors as in the previous version of the code. As per Zendeks, 503 retries are supposed to be done only when the retry headers mentions it, but that is against the implementation of previous version of code.
- 
- 

Bump version 1.7.3

---

.circleci/config.yml

Move build time to avoid conflicts with contractors and internal teams.
6:00am  UTC -> 1:00 UTC (8:00pm EST, 6:30am IST)
Move slack notifications to new channel.
- 
- 

change regression build runtime

---

test/test_pagination.py

- Generated enough records to pass the pagination test.
- Removed workaround from pagination test.
**Note:** Created [TDL-16941](https://jira.talendforge.org/browse/TDL-16941) for long-term solution to create `tags` record once token with write permission updated in circle-ci.
- 
- 

TDL-16912 Fix pagination test failure

---

test/test_pagination.py

Removed `tags` from pagination test until stabilization work can be picked up 
Backlog Ticket: https://jira.talendforge.org/browse/TDL-17980
- 
- 

remove tags from pagination test

---

tap_zendesk/http.py
test/unittests/test_http.py

(write a short description or paste a link to JIRA)
- Added support for backoff and retry for error 409
- updated unit test for same 
- formatted code using black plugin for http.py
- 
- 

TDL-18751:[tap-zendesk] Implement backoff to handle 409 from Zendesk API

---

test/base.py

Fix tap-tester test stability with a workaround for the consistent Connection Pool Errors from zendesk API.
Implemented backoff wrapper on the method call to execute sync, will retry if the HTTPSConnectionPool error is returned int he tap_error_message. 
- Ran code with debugger and overrode the the exit status with one from a failed build job to ensure retry logic catches the erorr.
- There is a potential that this could hide bugs or other test stability issues.

add backoff to the sync execution job in tests workaround ssl timeouts

---

.circleci/config.yml
test/test_all_streams.py
test/test_bookmarks.py
test/test_minimal_selection.py

Save test artifacts.
Ensure HTTPConnectionPool Error test workaround (retry on failed sync due specific error) is used in all tests.
- 
- 

save test artifacts

---

test/base.py

Increase timedelta to set bookmark back 2 hours instead of 1 hour in an effort to assure all streams get data for the second sync.  Previously it was seen that an empty second sync could occur on rare occasion.
- 
- 

increase timedelta to increase chance of all streams having data to sync

---

test/test_all_streams.py

The tags stream is FULL_TABLE but data for the stream ages out automatically if a tag has not been used for 60 days.  To increase test coverage and put this stream under test the test_all_streams.py file was updated to use the zenpy client to refresh tags every time it runs.
https://jira.talendforge.org/browse/TDL-20398
- 
- 

Auto-refresh the tags stream to prevent data age out

---

test/test_all_streams.py
test/test_standard_bookmark.py
test/test_start_date.py

WIP add satisfaction_ratings stream to test coverage
- 
- 

TDL-17980 add satisfaction_ratings stream to test coverage

---

CHANGELOG.md
setup.py
tap_zendesk/streams.py
test/unittests/test_user_infinite_loop.py

- Reproduce infinite loop behavior in unit test 'test_user_infinite_loop.py' and correct that behavior
- Infinite behavior not happened if single second has more than 1000 records.
- 

TDL-6756:  Fix Infinite Loop for Users

---

.circleci/config.yml
CHANGELOG.md
setup.py
tap_zendesk/__init__.py
tap_zendesk/http.py
test/unittests/test_http.py

Adds backoff/retries for 
- `urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`
- `requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))`
- 
- Low

Backoff for Protocol error and chunked encoding errors

---

.circleci/config.yml
tap_zendesk/__init__.py
tap_zendesk/http.py
test/base.py
test/unittests/test_http.py

Duplicates #131 for all the connections using 1.x versions
Adds backoff for ChunkedEncodingError, ProtocolError and ConnectionResetError
```
- urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
- requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```
- 
- Low

add backoff for ConnectionResetError, ChunkedEncodingError and ProtocolError

---

CHANGELOG.md
setup.py
tap_zendesk/http.py
tap_zendesk/streams.py
test/unittests/test_http.py
test/unittests/test_request_timeout.py

- A page size of 100 can sometimes be too large for zendesk to handle.
- Page size is now an advanced option, with a default value of 100.
- can be set to any integer between 1 and 1000 (inclusive)
- Verified adjusting page size down will lead to a successful response from Zendesk
- Values outside of 1 - 1000 will cause the default page size (100) to be used
- Low. Only requests that were previously using page size will use the custom page size, if specified.

Get page_size from config or use default

---

test/test_all_fields.py
test/test_lookup_fields.py

Remove chat_only field from expectations again
- 
- 

Remove chat_only field from expectations again

---

tap_zendesk/http.py
tap_zendesk/streams.py
test/unittests/test_async_ticket_audits.py
test/unittests/test_http.py

- Add backoff for 5xx errors.
- Reduce concurrent request limit to 20.
- Make a maximum of 450 ticket_audit([an endpoint specific rate limit](https://developer.zendesk.com/api-reference/introduction/rate-limits/#endpoint-rate-limits:~:text=List%20Audits%20for,requests%20per%20minute)) API calls per minute. If it hits 450 call within a minute, then wait for the  remaining seconds.
- Run the sync mode and verify that the tap hits a max of 20 concurrent requests at a time.
- Run the sync mode and verify that tap retries on any 5xx errors.
- 
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code

TDL-26714: Fix ratelimit error and add retry for 5xx errors

---

CHANGELOG.md
setup.py

- Upgrade aiohttp and requests lib versions to `3.11.9` and `2.32.3` respectively.
- 
- 
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code

Upgrade aiohttp and requests lib version

---

CHANGELOG.md
setup.py
tap_zendesk/streams.py

We are using this [search](https://developer.zendesk.com/api-reference/ticketing/ticket-management/search/?_gl=1*1kjhwjj*_ga*NjA2MTA1ODg0LjE3NDQ3MTg3NDI.*_ga_0G6FC9CS2V*MTc0NDcxODg3OS4xLjEuMTc0NDcyMDM2Mi41Ni4wLjA.#export-search-results) endpoint, which returns up to 1000 results per query with a maximum of 100 results per page. If we request past the limit, a 422 response is expected according to this [reference](https://support.zendesk.com/hc/en-us/community/posts/4409222763930-API-error-Invalid-search-Requested-response-size-was-greater-than-Search-Response-Limits).
So, replace the endpoint with the [list-macros](https://developer.zendesk.com/api-reference/ticketing/business-rules/macros/#list-macros) endpoint, which will fetch all the `macros` records without any error.
- 
- 
- revert …

Fix incremental extraction issue for macros

---

tap_zendesk/streams/__init__.py
tap_zendesk/streams/activities.py
tap_zendesk/streams/audit_logs.py

This PR covers sync implementation for streams:
- activities
- audit_logs

[SAC-28940]- Sync implementation for `activities` and `audit_logs` streams
